base_lr: 0.01
batch_size: 128
checkpoint_file: ''
config: ./config/train_config.yaml
continue_training: false
debug: true
device: 0
eval_interval: 2
ignore_weights: []
log_interval: 100
model: model.agcn_3d_coarse_to_fine.Model
model_args: {}
model_saved_name: ./save_model/ref_old_dis_noise_v2/ref_old_dis_noise_k10_nll_0.5dloss_npair_v2
nesterov: true
num_epoch: 100
num_worker: 8
only_train_epoch: 0
only_train_part: false
optimizer: Adam
print_log: true
save_interval: 2
seed: 1
show_topk:
- 1
- 5
start_epoch: 0
step:
- 20
- 50
- 80
test_batch_size: 128
test_data_path1: data/resize_BIWI/
test_data_path2: data/resize_AFLW2000/
test_dataset1: BIWI
test_dataset2: AFLW2000
test_file_name1: filelist/resize_BIWI_test_p1.txt
test_file_name2: filelist/AFLW2000.txt
test_loop: false
train_data_path: data/resize_300W_LP/
train_dataset: Pose_300W_LP
train_file_name: filelist/300W_LP.txt
valid_data_path: data/SynergyNet/300W_LP/
valid_dataset: Pose_300W_LP
valids_file_name: filelist/300W_LP-3D.txt
warm_up_epoch: 0
weight2: null
weight_decay: 1.0e-06
weights: null
weights_file: ''
weights_file_extract: ./save_model/pullback/pullback.pt
work_dir: ./work_dir/retrain/FAN/3D/FAN_21LM_3D_1S_N0.5_normalized_remove
